### ISSUE TITLE
Display the Profile picture from the User`s Spotify Account

### ISSUE THREAD

**Issue by StinkyGrandpa** [StinkyGrandpa/yt-spotify-converter#13]
Provide the image source to the Frontend. The Image source can be fetched vie the Profile Informations from the Spotify API.

This Project uses already this Spotify Endpoint.

### What has to be done?

Provide the Image Source to the Frontend via the UsersProfileInfoDTO

**Comment by z3ttee** [comment]
Du ronny, klopp nich immer mitm bello irwelche issues hier rein
