### ISSUE TITLE
Retrieve Playlist + Song images/covers

### ISSUE THREAD

**Issue by z3ttee** [StinkyGrandpa/yt-spotify-converter#6]
**Me as** UI User **want to** see images on playlists and the cover of songs in the overview **to** better identify playlists and for asthetic reasons.

### **What needs to be done on the BE?**
The Back-End (BE), in this case our NestJS endpoints for playlist and song retrieval, need to add information on images for playlists and songs. Spotify is providing such information.

### **What needs to be done on the FE**
The Front-End (FE), in this case the Angular Application, has to load the images based on the information provided by the BE calls. This can be a url or something similar.

**Comment by StinkyGrandpa** [comment]
Thanks for the very good descriped User Story!

Ive Provided the Image sources to you!

Pls style them (they are very large)

**Comment by z3ttee** [comment]
Back End task is done.
See PR #12

**Comment by z3ttee** [comment]
This feature is done.
See #19
